development:
  sessions:
    default:
      database: minerva_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: minerva_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0